#FROM 'docker.io/bitnami/rabbitmq:3.8-debian-10'
FROM 'gitlab.elia.academy:5050/root/elia/bitnami/rabbitmq:3.8-debian-10'
RUN rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_federation_management rabbitmq_stomp
