apiVersion: v1
kind: ConfigMap
metadata:
  name: elia-search-engine-interface
data:
  ELASTICSEARCH_URL: local-elia-search-engine.local.svc.cluster.local:9200
  ELASTICSEARCH_HOSTS: http://local-elia-search-engine.local.svc.cluster.local:9200