module.exports = [
    "Home",
    "Admin - Authorization",
    "Admin - Teams Access",
    "Admin - Credits",
    "My Teams - Teams",
    "My Teams - BC Test Registrations",
    "My Teams - Results",
    "My Teams - Statistics",
    // "My Team - BC Results for Team - NAD/QNAD",
    // "My Team - BC Results for Team - strong/weak points",
    // "My Team - BC Results for Team - interpersonal dimensions",
    // "My Team - BC Results for Team - intrapersonal dimensions",
    // "My Team - BC Results for Team - emotional intelligence",
    // "My Team - BC Results for Team - cost/time report",
    "My Users - Users",
    "My Users - BC Test Registrations",
    "My Projects",
    "My Diary",
    "My Trainings - BrainCore Coach",
    "My Trainings - BrainCore Trainer",
    // "Interactive CS - authomatized projects - potential group",
    // "Interactive CS - authomatized projects - suggested solution",
    // "Interactive CS - authomatized projects - group solution selection",
    // "Interactive CS - authomatized projects - follow up project creation",
    // "Interactive CS - recruting",
    // "Interactive CS - custom projects",
    // "Interactive CS - employee management",
    // "Neuro Functions - dysfunctioning groups matrix",
    // "Neuro Functions - team creation",
    // "Neuro Functions - career project",
    // "Neuro Functions - psy risks (quiet quitter/opportunist)",
    // "Neuro Functions - behaviourist matrix",
    // "Neuro Functions - management style advices",
    // "Neuro Functions - gamification/contests",
    "My Space - My Results",
    "My Space - Virtual Coach",
    "My Space - My Resources"
];