apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - basic-auth-secret.yaml
  - ../base

patches:
  - target:
      kind: Ingress
      name: ingress-grafana
    path: ingress-grafana-patch.json
  - target:
      kind: Ingress
      name: ingress-prometheus
    path: ingress-prometheus-patch.json