apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: translator

resources:
  - svc.yaml
  - deploy.yaml
  - configmap.yaml
  - basic-auth-middleware.yaml
  - ingress-translator.yaml