apiVersion: v1
kind: ConfigMap
metadata:
  name: elia-search-engine
data:
  ES_JAVA_OPTS: -Xms512m -Xmx512m
  bootstrap.memory_lock: "true"
  cluster.name: es-docker-cluster
  discovery.type: single-node
  node.name: es01