apiVersion: v1
kind: PersistentVolume
metadata:
  name: search-engine-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/local/search-engine"
