exports.subinterests = [
    {'name': 'Economy', '_id': 1, 'interest': 1} ,
    {'name': 'Entrepreneurship', '_id': 2, 'interest': 1} ,
    {'name': 'Law', '_id': 3, 'interest': 1} ,
    {'name': 'Management', '_id': 4, 'interest': 1} ,
    {'name': 'Money', '_id': 5, 'interest': 1} ,
    {'name': 'Personal developement', '_id': 6, 'interest': 1} ,
    {'name': 'Art', '_id': 7, 'interest': 2} ,
    {'name': 'DIY', '_id': 8, 'interest': 2} ,
    {'name': 'Books', '_id': 9, 'interest': 2} ,
    {'name': 'Dance', '_id': 10, 'interest': 2} ,
    {'name': 'Design', '_id': 11, 'interest': 2} ,
    {'name': 'Film', '_id': 12, 'interest': 2} ,
    {'name': 'Music', '_id': 13, 'interest': 2} ,
    {'name': 'Philosophy', '_id': 14, 'interest': 2} ,
    {'name': 'Theatre', '_id': 15, 'interest': 2} ,
    {'name': 'Architecture', '_id': 16, 'interest': 3} ,
    {'name': 'Psychology', '_id': 17, 'interest': 3} ,
    {'name': 'Art', '_id': 18, 'interest': 3} ,
    {'name': 'Computer Science', '_id': 19, 'interest': 3} ,
    {'name': 'English', '_id': 20, 'interest': 4} ,
    {'name': 'French', '_id': 21, 'interest': 4} ,
    {'name': 'German', '_id': 22, 'interest': 4} ,
    {'name': 'Animals', '_id': 23, 'interest': 5} ,
    {'name': 'Biology', '_id': 24, 'interest': 5} ,
    {'name': 'Climate change', '_id': 25, 'interest': 5} ,
    {'name': 'Economy', '_id': 26, 'interest': 5} ,
    {'name': 'Geography', '_id': 27, 'interest': 5} ,
    {'name': 'Plants', '_id': 28, 'interest': 5} ,
    {'name': 'Biology', '_id': 29, 'interest': 6} ,
    {'name': 'Chemistry', '_id': 30, 'interest': 6} ,
    {'name': 'Data science', '_id': 31, 'interest': 6} ,
    {'name': 'Health', '_id': 32, 'interest': 6} ,
    {'name': 'Medicine', '_id': 33, 'interest': 6} ,
    {'name': 'Physics', '_id': 34, 'interest': 6} ,
    {'name': 'Space and astronomy', '_id': 35, 'interest': 6} ,
    {'name': 'Activism', '_id': 36, 'interest': 7} ,
    {'name': 'Civil Rights', '_id': 37, 'interest': 7} ,
    {'name': 'Geography', '_id': 38, 'interest': 7} ,
    {'name': 'Climate change', '_id': 39, 'interest': 7} ,
    {'name': 'Economy', '_id': 40, 'interest': 7} ,
    {'name': 'Ethnography', '_id': 41, 'interest': 7} ,
    {'name': 'Media', '_id': 42, 'interest': 7} ,
    {'name': 'Politics', '_id': 43, 'interest': 7} ,
    {'name': 'Reforms', '_id': 44, 'interest': 7} ,
    {'name': 'Feminism', '_id': 45, 'interest': 7} ,
    {'name': 'Religion', '_id': 46, 'interest': 7} ,
    {'name': 'Travel', '_id': 47, 'interest': 7} ,
    {'name': 'Sociology', '_id': 48, 'interest': 7} ,
    {'name': 'Economy', '_id': 49, 'interest': 8} ,
    {'name': 'Activism', '_id': 50, 'interest': 8} ,
    {'name': 'Climate change', '_id': 51, 'interest': 8} ,
    {'name': 'Historical changes in Europe', '_id': 52, 'interest': 8} ,
    {'name': 'Education', '_id': 53, 'interest': 8} ,
    {'name': 'History', '_id': 54, 'interest': 8} ,
    {'name': 'Law', '_id': 55, 'interest': 8} ,
    {'name': 'Civil Rights', '_id': 56, 'interest': 8} ,
    {'name': 'Politics', '_id': 57, 'interest': 8} ,
    {'name': 'Reforms', '_id': 58, 'interest': 8} ,
    {'name': 'Media', '_id': 59, 'interest': 8} ,
    {'name': 'AI', '_id': 60, 'interest': 9} ,
    {'name': 'Coding', '_id': 61, 'interest': 9} ,
    {'name': 'Data science', '_id': 62, 'interest': 9} ,
    {'name': 'Mathematics', '_id': 63, 'interest': 9} ,
    {'name': 'Engineering', '_id': 64, 'interest': 9} ,
    {'name': 'Entrepreneurship', '_id': 65, 'interest': 9} ,
    {'name': 'IT', '_id': 66, 'interest': 9} ,
    {'name': 'Mathematic in use', '_id': 67, 'interest': 9} ,
    {'name': 'Technology', '_id': 68, 'interest': 9} ,
    {'name': 'DIY', '_id': 69, 'interest': 10} ,
    {'name': 'Diet', '_id': 70, 'interest': 10} ,
    {'name': 'Disciplines', '_id': 71, 'interest': 10} ,
    {'name': 'Trainings', '_id': 72, 'interest': 10} ,
    {'name': 'Creativity', '_id': 73, 'interest': 10} ,
    {'name': 'Food', '_id': 74, 'interest': 10} ,
    {'name': 'Health', '_id': 75, 'interest': 10} ,
    {'name': 'Medicine', '_id': 76, 'interest': 10} ,
    {'name': 'Personal developement', '_id': 77, 'interest': 10} ,
    {'name': 'Nutrition', '_id': 78, 'interest': 10} ,
    {'name': 'Psychology', '_id': 79, 'interest': 10} ,
    {'name': 'Religion', '_id': 80, 'interest': 10} ,
    {'name': 'Sport', '_id': 81, 'interest': 10} ,
    {'name': 'Travel', '_id': 82, 'interest': 10} ,
    {'name': 'Philosophy', '_id': 83, 'interest': 10} ,
    {'name': 'School subjects', '_id': 84, 'interest': 11} ,
    {'name': 'Science', '_id': 85, 'interest': 11} ,
    {'name': 'History', '_id': 86, 'interest': 11}        
]