apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: translator

resources:
  - ../base
  - basic-auth-secret.yaml

patches:
  - target:
      kind: Ingress
      name: ingress-translator
    path: ingress-translator-patch.json