apiVersion: v1
kind: PersistentVolume
metadata:
  name: message-broker-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/local/message-broker"
