apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
namespace: prod

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: maintenance-ingress
    path: ingress-maintenance-patch.json

