apiVersion: skaffold/v2beta17
kind: Config

deploy:
  kustomize:
    paths:
    - k8s/base

profiles:
  - name: local
    build:
      artifacts:
        - image: elia-backend
          docker:
            buildArgs:
              BACKEND_ENV: development
          sync:
            manual:  
              - src: 'app/**'
                dest: app
                strip: 'app'
              - src: 'tests/*'
                dest: tests
                strip: 'tests'
      local:
        push: true
    deploy:
      kustomize:
        paths:
          - k8s/local
  - name: test
    build:
      artifacts:
        - image: elia-backend
          docker:
            buildArgs:
              BACKEND_ENV: development
      local:
        push: true
    deploy:
      kustomize:
        paths:
          - k8s/test
  - name: dev
    build:
      artifacts:
        - image: elia-backend
          docker:
            buildArgs:
              BACKEND_ENV: development
      local:
        push: true
    deploy:
      kustomize:
        paths:
          - k8s/dev
  - name: stage-evvo
    build:
      artifacts:
        - image: elia-backend
          docker:
            buildArgs:
              BACKEND_ENV: production
      local:
        push: true
    deploy:
      kustomize:
        paths:
          - k8s/stage-evvo
  - name: local-dev-evvo
    build:
      artifacts:
        - image: elia-backend
          docker:
            buildArgs:
              BACKEND_ENV: development
      local:
        push: true
    deploy:
      kustomize:
        paths:
          - k8s/local-dev-evvo
  - name: demo
    build:
      artifacts:
        - image: elia-backend
          docker:
            buildArgs:
              BACKEND_ENV: development
      local:
        push: true
    deploy:
      kustomize:
        paths:
          - k8s/demo
  - name: stage
    build:
      artifacts:
        - image: elia-backend
          docker:
            buildArgs:
              BACKEND_ENV: production
      local:
        push: true
    deploy:
      kustomize:
        paths:
          - k8s/stage
  - name: prod-ch
    build:
      artifacts:
        - image: elia-backend
          docker:
            buildArgs:
              BACKEND_ENV: production
      local:
        push: true
    deploy:
      kustomize:
        paths:
          - k8s/prod/ch
  - name: prod-fr
    build:
      artifacts:
        - image: elia-backend
          docker:
            buildArgs:
              BACKEND_ENV: production
      local:
        push: true
    deploy:
      kustomize:
        paths:
          - k8s/prod/fr
  - name: prod-evvo
    build:
      artifacts:
        - image: elia-backend
          docker:
            buildArgs:
              BACKEND_ENV: production
      local:
        push: true
    deploy:
      kustomize:
        paths:
          - k8s/prod/evvo
