apiVersion: v1
kind: ConfigMap
metadata:
  name: elia-search-engine-interface
data:
  ELASTICSEARCH_URL: dev-elia-search-engine.dev.svc.cluster.local:9200
  ELASTICSEARCH_HOSTS: http://dev-elia-search-engine.dev.svc.cluster.local:9200
