apiVersion: v1
kind: Secret
metadata:
  name: elia-main-secret
stringData:
  # database
  MONGO_INITDB_PASSWORD: Testing123!
  MONGO_INITDB_ROOT_PASSWORD: Testing123!

  # database-interface
  ME_CONFIG_BASICAUTH_PASSWORD: Testing123!
  ME_CONFIG_MONGODB_AUTH_PASSWORD: Testing123!

  # message-broker
  RABBITMQ_DEFAULT_PASS: Testing123!

  # task-executor
  MESSAGE_BROKER_DEFAULT_PASS: Testing123!
  
  # mail
  SMTP_PASSWORD: Testing123!

  # secret JWT
  SECRET_KEY: d8b94303f450651a2d789e55005c94f569a09d7b2191acbe4d279d570d5c9afe

  # paypal
  PAYPAL_CLIENT_ID: AZtJxslfO8yZTw_tMvFPq-yfHSa8LP4gw9QR05YziSwwWBDfbnxH0XvENIq1msxKqroVk_ZVwyoC5aMJ
  PAYPAL_SECRET: EO67RA5wsqDo_TGApkAC_BiKUZ06c490_SOtGoD-4EEIBvs2ha_CqHDb6dnoqCEFZJrBgy0uYmKLNBEh

  PAYPAL_INVOICER_EMAIL: sb-demt91157649@business.example.com
  PAYPAL_INVOICER_COMPANY_ID: '2013123123123'
  PAYPAL_INVOICER_COMPANY_NAME: 'Ecole Test'
  PAYPAL_INVOICE_TAX_PERCENTAGE: '20'


  #SendGrid
  SENDGRID_API_KEY: 'xxxxxxxxxxxxN8Ussh4w._7fzxiju9quIBZatZ7TWuFqetEL7l7pvPnOJi0HbrJM'
  SENDGRID_FROM: 'here@put.your_email'