apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-certificates
spec:
  # Secret names are always required.
  secretName: monitoring-certificates
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    - fr.grafana.elia.academy
    - fr.prometheus.elia.academy
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer