apiVersion: v1
kind: ConfigMap
metadata:
  name: elia-backend
data:
  BACKEND_ENV: development
  MESSAGE_BROKER_HOST: demo-elia-message-broker.demo.svc.cluster.local
  SEARCH_ENGINE_HOST: demo-elia-search-engine.demo.svc.cluster.local
  #DATABASE connection
  DATABASE_HOST: demo-elia-database.demo.svc.cluster.local

  ELIA_ALGORITHMS_URL: https://evvo:algorithms-evvo-password@algorithms.elia.academy
  ELIA_BLOCKCHAIN_URL: http://demo-elia-blockchain-api.demo.svc.cluster.local:3000