apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- ingress-backend.yaml
- ingress-frontend.yaml
- ingress-database-interface.yaml
- ingress-search-engine-interface.yaml
- basic-auth-middleware.yaml
- https-middleware.yaml

commonLabels:
  app: elia-proxy