apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local
namePrefix: local-

resources:
  - ../base

patches:
  - target:
      kind: Deployment
      name: elia-frontend
    path: deploy-patch.json