apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elia-dev-certificates
  namespace: dev
spec:
  # Secret names are always required.
  secretName: elia-dev-certificates
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    - dev.elia.academy
    - database-interface.dev.elia.academy
    - search-engine-interface.dev.elia.academy
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer