apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elia-prod-certificates
  namespace: prod
spec:
  # Secret names are always required.
  secretName: elia-prod-certificates
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    - marketing.braincore.app
    - nemesis.braincore.app
    - company1.braincore.app
    - las.braincore.app
    - database-interface.braincore.app
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer