apiVersion: v1
kind: ConfigMap
metadata:
  name: elia-backend
data:
  BACKEND_ENV: development

  MESSAGE_BROKER_DEFAULT_USER: root
  MESSAGE_BROKER_HOST: local-elia-message-broker.local.svc.cluster.local
  SEARCH_ENGINE_HOST: local-elia-search-engine.local.svc.cluster.local
  SEARCH_ENGINE_PORT: "9200"
  FCM_SERVER_KEY: AAAAkuZ7KKo:APA91bFm8xwdl4QGTP-ZNIU3wV6Vb8cMdaDXdaS4u2Hv65sMH5Pl6_RsH0jcYAGfCPPtEJhmuNe51UZrZByxqmRlN_ZlV2Y8nhDCEGWKEN5ucCiEfMHltg2yJgGJFCSx2kjRNAsykRdt



  #DATABASE connection
  DATABASE_HOST: local-elia-database.local.svc.cluster.local
  DATABASE_PORT: "27017"
  MONGO_INITDB_DATABASE: elia
  MONGO_INITDB_USERNAME: elia

  MONGO_INITDB_TEST_DATABASE: test_elia
  #ELIA_ALGORITHMS_URL: http://local-elia-algorithms.local.svc.cluster.local:5000
  ELIA_ALGORITHMS_URL: https://evvo:algorithms-evvo-password@algorithms.elia.academy
  
  # For blockchain service from dev environment use http://65.108.147.12:30300
  ELIA_BLOCKCHAIN_URL: http://local-elia-blockchain-api.local.svc.cluster.local:3000

  # Big Blue Button
  BIG_BLUE_BUTTON_URL: https://conference-tool.elia.academy/
  BIG_BLUE_BUTTON_SECRET: reiyhYnGItkfCCLzw7IjRfiiTZlNJSPolbkWSjl3

  # Chromium DRIVER FOR PDF GENERATION
  CHROMIUM_BROWSER_PATH: '/usr/bin/chromium-browser'