apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  app: elia-backend

resources:
  - pv.yaml
  - pvc.yaml
  - svc.yaml
  - deploy.yaml
  - configmap.yaml

