apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: stage-
namespace: stage

resources:
  - ../base

patches:
  - target:
      kind: Ingress
      name: maintenance-ingress
    path: ingress-maintenance-patch.json

