apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: translator-certificates
spec:
  # Secret names are always required.
  secretName: translator-certificates
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    - translator.elia.academy
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer